title: 我的博客
email: your-email@example.com
description: >-
  这是我的个人博客，分享技术、生活和思考。

baseurl: ""
url: "https://hugh-ho.github.io"

twitter_username: username
github_username: hugh-ho

markdown: kramdown
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme
