title: 时间的朋友
email: maidongcao.up@gmail.com
description: >-
  时间看得见，知识会沉淀

baseurl: ""
url: "https://hugh-ho.github.io"

twitter_username: maidongcao
github_username: hugh-ho

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

collections:
  category:
    output: true
    permalink: /categories/:name/
